steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/originhub-frontend:$COMMIT_SHA"
      - "-t"
      - "gcr.io/$PROJECT_ID/originhub-frontend:latest"
      - "."
    timeout: "1200s"

# Note: All environment variables should be set in Cloud Run (Variables & Secrets tab)
# Required: CLERK_SECRET_KEY, NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY, NEXT_PUBLIC_API_URL
# Optional: NEXT_PUBLIC_CLERK_DOMAIN

images:
  - "gcr.io/$PROJECT_ID/originhub-frontend:$COMMIT_SHA"
  - "gcr.io/$PROJECT_ID/originhub-frontend:latest"

options:
  machineType: "E2_HIGHCPU_8"
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
