steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--build-arg"
      - "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${_NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}"
      - "--build-arg"
      - "NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}"
      - "--build-arg"
      - "CLERK_SECRET_KEY=${_CLERK_SECRET_KEY}"
      - "-t"
      - "gcr.io/$PROJECT_ID/originhub-frontend:$COMMIT_SHA"
      - "-t"
      - "gcr.io/$PROJECT_ID/originhub-frontend:latest"
      - "."
    timeout: "1200s"
    secretEnv:
      [
        "_NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY",
        "_NEXT_PUBLIC_API_URL",
        "_CLERK_SECRET_KEY",
      ]

images:
  - "gcr.io/$PROJECT_ID/originhub-frontend:$COMMIT_SHA"
  - "gcr.io/$PROJECT_ID/originhub-frontend:latest"

options:
  machineType: "E2_HIGHCPU_8"
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
